// Declarative Syntax to describe that come

// JAVASCRIPT XML - EXTENSION TO THE JAVASCRIPT LANGUAGE SYNTAX 
// WRITE A XML - LIKE CODE FOR ELEMENTS AND COMPONENTS 
// JSX TAGS HAVE A TAG NAME ATTRIBUTES AND CHILDREN  
// JSX IS NOT A NECESSITY TO WRITE REACT APPLICATIONS 
// JSX MAKE YOUR REACT CODE SIMPLER AND AGENT 
// JSX ULITMATELY TRANSPILES TO PURE JAVASCRIPT WHICH IS UNDERSTOOD BY THE BROWSERS
